Support for custom makepkg.conf (https://bugs.archlinux.org/task/40946 is not implemented in makechrootpkg)

diff --git a/common/clean-chroot-manager64.in b/common/clean-chroot-manager64.in
--- a/common/clean-chroot-manager64.in
+++ b/common/clean-chroot-manager64.in
@@ -140,6 +140,8 @@ check() {
       export TESTING="Enabled"
     fi
   fi
+  
+  MAKEPKG_CONFIG=""
 }
 
 create() {
@@ -200,6 +202,9 @@ create() {
 
   # do the same for gcc errors
   sed -i -e 's/size=4/size=4 -fdiagnostics-color/g' "$CHROOTPATH64"/root/etc/makepkg.conf
+  
+  # backup makepkg.conf
+  cp "$CHROOTPATH64"/root/etc/makepkg.conf "$CHROOTPATH64"/root/etc/makepkg.conf.org
 }
 
 check2() {
@@ -238,6 +243,17 @@ build() {
     args+=(-n)
   fi
 
+  if [[ -n "$MAKEPKG_CONFIG" ]]; then
+    if [[ ! -f "$MAKEPKG_CONFIG" ]]; then
+      local mesg="makepkg config $MAKEPKG_CONFIG does not exist."
+      echo -e "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}"
+      exit 1
+    fi
+    cp "$MAKEPKG_CONFIG" "$CHROOTPATH64"/root/etc/makepkg.conf
+  else
+    cp "$CHROOTPATH64"/root/etc/makepkg.conf.org "$CHROOTPATH64"/root/etc/makepkg.conf
+  fi
+  
   if ! PACKAGER=$PACKAGER MAKEFLAGS=-j$THREADS nice -19 /usr/bin/makechrootpkg "${args[@]}"; then
     exit 1
   fi
@@ -468,6 +484,16 @@ distcc_check() {
 }
 
 check
+
+# get switches
+args=("$@")
+for (( a = 0; a < $#; a++ )); do
+  if [[ ${args[$a]} == -c=* ]]; then
+    MAKEPKG_CONFIG=${args[$a]#*=}
+  elif [[ ${args[$a]} == -* ]]; then
+    echo "Invalid Argument" && exit 1
+  fi
+done
 
 case "$1" in
   a)
